### ISSUE TITLE
Workflow for Grafana

### ISSUE THREAD

**Issue by kaihendry** [alexdglover/jsonnet-render#3]
Hi, I'm looking for a workflow where by I create jsonnet depending on https://github.com/grafana/jsonnet-libs/blob/master/grafana-builder/grafana.libsonnet where by the artifact is deployed to grafana somehow and used as a dashboard.

Is this work flow appropriate or should I be looking elsewhere? Thank you in advance

**Comment by alexdglover** [comment]
This repo defines an action that can be used in a GItHub Actions™ workflow. it is just one component of a workflow, it does not comprise a workflow by itself.

This action simply executes the `jsonnet` command with a set of command line arguments. Generally this means taking some Jsonnet files as inputs and outputting JSON/YAML files. It does not _create_ Jsonnet code, it just _evaluates_ Jsonnet code.

If rendering Jsonnet files into JSON/YAML is what you're trying to do, then yes, this action is appropriate. To be honest I don't understand the rest of your use case. Hope this helps.
